---
#
# This playbook raise cpu number for a VM
#
- name: Raise cpu number for a VM
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_ip
      prompt: vCenter IP or hostname
      private: no

    - name: vcenter_username
      prompt: vCenter username
      private: no

    - name: vcenter_password
      prompt: vCenter password
      private: yes

    - name: datacenter
      prompt: VMWare datacenter
      private: no

    - name: vm_name
      prompt: VM Name
      private: no

    - name: memory_size
      prompt: Size of memory
      private: no

  tasks:
  - name: "Get VM info"
    community.vmware.vmware_guest_info:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vm_name }}"
    register: vm_info
    delegate_to: localhost
    connection: local

  - name: "Raise memory size for a VM"
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      uuid: "{{ vm_info.instance.hw_product_uuid }}"
      hardware:
        memory_mb: "{{ memory_size|int * 1024 }}"
    when: (memory_size|int * 1024) > vm_info.instance.hw_memtotal_mb
    delegate_to: "localhost"
    connection: local

  - name: "Requested memory should be larger than existent"
    debug:
      msg: "Requested memory should be larger than existent ( {{ (memory_size|int * 1024) }} <= {{ vm_info.instance.hw_memtotal_mb }} !)"
    when: (memory_size|int * 1024) <= vm_info.instance.hw_memtotal_mb
